#!/usr/bin/env ruby
require 'erb'
require 'fileutils'

def build_file(version, checksum, file)
  File.write(file, ERB.new(File.read("template/#{file}.erb")).result(binding))
end

def build_files(version, checksum)
  `git checkout master`
  `git branch -d #{version}`
  `git checkout -b #{version}`
  %w(Dockerfile sha256sums).each do |file|
    build_file(version, checksum, file)
  end
  `git add .`
  `git commit --amend --no-edit`
end

VERSIONS = {
  '2.2.0' => '7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc',
  '2.1.5' => '4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100',
  '2.0.0-p643' => '4136bf7d764cbcc1c7da2824ed2826c3550f2b62af673c79ddbf9049b12095fd',
}

if ARGV[0]
  fail unless VERSIONS[ARGV[0]]
  build_files(ARGV[0],VERSIONS[ARGV[0]])
else
  VERSIONS.each do |version, checksum|
    build_files(version, checksum)
  end
end
