FROM quay.io/assemblyline/buildpack_deps:14.04

ENV RUBY_VERSION <%= data['version'] %>
COPY sha256sums /usr/src/ruby/

RUN apt-get update -q \
      && apt-get install -qy bison ruby nodejs --no-install-recommends \
      && rm -rf /var/lib/apt/lists/* \
      && mkdir -p /usr/src/ruby \
      && curl -o /usr/src/ruby/src.tar.gz --create-dirs http://cache.ruby-lang.org/pub/ruby/<%= data['version'][0..2] %>/ruby-<%= data['version'] %>.tar.gz \
      && cd /usr/src/ruby \
      && sha256sum -c sha256sums \
      && tar zxf src.tar.gz --strip-components=1 \
      && autoconf \
      && ./configure --disable-install-doc \
      && make -j"$(nproc)" \
      && make install \
      && apt-get purge -y --auto-remove bison ruby \
      && echo 'gem: --no-document' > /etc/gemrc \ 
      && gem update --system \
      && gem install bundler \
      && rm -r /usr/src/ruby
